apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-helm-guestbook
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen:
      activeService: blue-green-helm-guestbook
      previewService: blue-green-helm-guestbook-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: blue-green-helm-guestbook
  template:
    metadata:
      labels:
        app: blue-green-helm-guestbook
    spec:
      containers:
        - name: guestbook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
