apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  labels:
    app: demo
    env: prod
spec:
  containers:
    - name: nginx
      image: myregistry.com/nginx:v1
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
      securityContext:
        runAsNonRoot: true
        privileged: false
      livenessProbe:
        httpGet:
          path: /
          port: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80