apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    # ---------------------------------------------------------
    # IMPORTANT: REPLACE THIS URL WITH YOUR NEW GITHUB REPO URL
    # ---------------------------------------------------------
    repoURL: https://github.com/akshayraina999/argo-cd.git
    targetRevision: main
    path: bootstrap/apps  # Pointing to the folder we made in Step 1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true