apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-worker-scaler
  namespace: kafka
spec:
  scaleTargetRef:
    name: redis-worker

  minReplicaCount: 1
  maxReplicaCount: 10

  triggers:
    - type: redis
      metadata:
        address: redis.kafka.svc.cluster.local:6379
        listName: jobs
        listLength: "5"   # scale when >5 jobs