# Policy: Require Health Probes
# Purpose: Ensures liveness and readiness probes are defined
# Benefit: Improves reliability and enables self-healing

# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: require-probes
# spec:
#   validationFailureAction: enforce
#   rules:
#     - name: check-probes
#       match:
#         resources:
#           kinds:
#             - Pod
#       validate:
#         message: "Liveness and readiness probes are required"
#         pattern:
#           spec:
#             containers:
#               - livenessProbe: {}
#                 readinessProbe: {}

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-probes
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - default
            - dev
            - staging
      exclude:
        resources:
          namespaces:
          - keda
          - kube-system
          - argocd
          - kyverno
          - keda
      validate:
        message: "Liveness and readiness probes are required."
        pattern:
          spec:
            containers:
              - livenessProbe:
                  httpGet:
                    path: "?*"
                    port: "?*"
                readinessProbe:
                  httpGet:
                    path: "?*"
                    port: "?*"