apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kafka
  labels:
    app: redis
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        env: dev
    spec:
      containers:
        - name: redis
          image: redis:7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kafka
  labels:
    app: redis
    env: dev
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379